"""add_more_company_fields

Revision ID: 474b46845531
Revises: da8a216bb298
Create Date: 2025-12-11 15:36:41.552944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474b46845531'
down_revision: Union[str, Sequence[str], None] = 'da8a216bb298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('email', sa.String(), nullable=True))
    op.add_column('places', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('places', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('places', sa.Column('province', sa.String(), nullable=True))
    op.add_column('places', sa.Column('suburb', sa.String(), nullable=True))
    op.add_column('places', sa.Column('service_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'service_type')
    op.drop_column('places', 'suburb')
    op.drop_column('places', 'province')
    op.drop_column('places', 'postal_code')
    op.drop_column('places', 'owner')
    op.drop_column('places', 'email')
    # ### end Alembic commands ###
